apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ugate
  namespace: ugate
  labels:
    release: ugate
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ugate
      release: ugate
