apiVersion: v1
kind: Service
metadata:
  name: wps
  namespace: wps
  labels:
    release: wps
spec:
  ports:
    - port: 5222
      name: tcp-ssh
    - port: 5228
      name: https
  selector:
    app: wps
---
