apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: wps
  namespace: wps
  labels:
    release: wps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: wps
      release: wps
