apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name:  ugate

build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04"

  artifacts:
    - image: grc.io/dmeshgate/ugate
      context: .

      sync:
        manual:
          - src: "../../www/**"
            dest: "www"

      custom:
        buildCommand: ../../bin/ko-build.sh
        dependencies:
          # Explicit - can also guess from Dockerfile
          paths:
            - "../../pkg/**"
            - "../../ext/**"
            - "."
            - "go.mod"
            - "go.sum"

deploy:
  kubectl:
    manifests:
      - ../../k8s/ugate/templates/*

portForward:
  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 5222
    localPort: 14022

  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 5227
    localPort: 14027

  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 15000
    localPort: 14000
