apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name:  ugate

build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04"

  artifacts:
    - image: costinm/ugate
      context: .

      sync:
        manual:
          - src: "../../www/**"
            dest: "www"

      custom:
        buildCommand: make build
        dependencies:
          paths:
            - "../../pkg/**"
            - "."
            - "go.mod"
            - "go.sum"

deploy:
  helm:
    releases:
      - name: ugate
        namespace: ugate
        createNamespace: true
        chartPath: ../../manifests/charts/ugate

portForward:
  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 5222
    localPort: 14022

  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 5227
    localPort: 14027

  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 15000
    localPort: 14000

  - resourceType: service
    namespace: mon
    resourceName: prometheus-1-grafana
    port: 80
    localPort: 3000

  - resourceType: service
    namespace: mon
    resourceName: prometheus-1-prometheus
    port: 9090
    localPort: 9090
  # Registry, for skaffold
#  - resourceType: replicationcontroller
#    namespace: kube-registry
#    resourceName: kube-registry-v0
#    port: 5000
#    localPort: 5000
  # Istio
#  - resourceType: service
#    namespace: istio-system
#    resourceName: istiod
#    port: 15010
#    localPort: 16010
