apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: ugate

build:
  # Expects a port forward from localhost:5001 to the actual registry.
  insecureRegistries:
    - localhost:5001

  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04"

  artifacts:
    # The base image can add debug tools and other utilities
    # The name must match what's in the manifest
    # Skaffold is mangling the names - so is ko, in different way
    # Bare image happens to work for both - but the manifest won't work.
    - image: ugate
      context: .

      # Pushed to pod instead of rebuild
      sync:
        manual:
          - src: "docs/**"
            dest: "."

#      custom:
#        buildCommand: ./bin/build.sh
#        dependencies:
#          paths:
#            - "**"

deploy:
  kubectl:
    manifests:
      - k8s/ugate/charts/*

portForward:
  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 5222
    localPort: 14022

  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 5227
    localPort: 14027

  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 15000
    localPort: 14000
