// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/costinm/dmesh/dm/istio/destination_rule.proto

package istio

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Standard load balancing algorithms that require no tuning.
type LoadBalancerSettings_SimpleLB int32

const (
	// Round Robin policy. Default
	LoadBalancerSettings_ROUND_ROBIN LoadBalancerSettings_SimpleLB = 0
	// The least request load balancer uses an O(1) algorithm which selects
	// two random healthy hosts and picks the host which has fewer active
	// requests.
	LoadBalancerSettings_LEAST_CONN LoadBalancerSettings_SimpleLB = 1
	// The random load balancer selects a random healthy host. The random
	// load balancer generally performs better than round robin if no health
	// checking policy is configured.
	LoadBalancerSettings_RANDOM LoadBalancerSettings_SimpleLB = 2
	// This option will forward the connection to the original IP address
	// requested by the caller without doing any form of load
	// balancing. This option must be used with care. It is meant for
	// advanced use cases. Refer to Original Destination load balancer in
	// Envoy for further details.
	LoadBalancerSettings_PASSTHROUGH LoadBalancerSettings_SimpleLB = 3
)

var LoadBalancerSettings_SimpleLB_name = map[int32]string{
	0: "ROUND_ROBIN",
	1: "LEAST_CONN",
	2: "RANDOM",
	3: "PASSTHROUGH",
}
var LoadBalancerSettings_SimpleLB_value = map[string]int32{
	"ROUND_ROBIN": 0,
	"LEAST_CONN":  1,
	"RANDOM":      2,
	"PASSTHROUGH": 3,
}

func (x LoadBalancerSettings_SimpleLB) String() string {
	return proto.EnumName(LoadBalancerSettings_SimpleLB_name, int32(x))
}
func (LoadBalancerSettings_SimpleLB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{3, 0}
}

// TLS connection mode
type TLSSettings_TLSmode int32

const (
	// Do not setup a TLS connection to the upstream endpoint.
	TLSSettings_DISABLE TLSSettings_TLSmode = 0
	// Originate a TLS connection to the upstream endpoint.
	TLSSettings_SIMPLE TLSSettings_TLSmode = 1
	// Secure connections to the upstream using mutual TLS by presenting
	// client certificates for authentication.
	TLSSettings_MUTUAL TLSSettings_TLSmode = 2
)

var TLSSettings_TLSmode_name = map[int32]string{
	0: "DISABLE",
	1: "SIMPLE",
	2: "MUTUAL",
}
var TLSSettings_TLSmode_value = map[string]int32{
	"DISABLE": 0,
	"SIMPLE":  1,
	"MUTUAL":  2,
}

func (x TLSSettings_TLSmode) String() string {
	return proto.EnumName(TLSSettings_TLSmode_name, int32(x))
}
func (TLSSettings_TLSmode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{6, 0}
}

// `DestinationRule` defines policies that apply to traffic intended for a
// service after routing has occurred. These rules specify configuration
// for load balancing, connection pool size from the sidecar, and outlier
// detection settings to detect and evict unhealthy hosts from the load
// balancing pool. For example, a simple load balancing policy for the
// ratings service would look as follows:
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       host: ratings.prod.svc.cluster.local
//       trafficPolicy:
//         loadBalancer:
//           simple: LEAST_CONN
//
// Version specific policies can be specified by defining a named
// `subset` and overriding the settings specified at the service level. The
// following rule uses a round robin load balancing policy for all traffic
// going to a subset named testversion that is composed of endpoints (e.g.,
// pods) with labels (version:v3).
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       host: ratings.prod.svc.cluster.local
//       trafficPolicy:
//         loadBalancer:
//           simple: LEAST_CONN
//       subsets:
//       - name: testversion
//         labels:
//           version: v3
//         trafficPolicy:
//           loadBalancer:
//             simple: ROUND_ROBIN
//
// **Note:** Policies specified for subsets will not take effect until
// a route rule explicitly sends traffic to this subset.
//
// Traffic policies can be customized to specific ports as well. The
// following rule uses the least connection load balancing policy for all
// traffic to port 80, while uses a round robin load balancing setting for
// traffic to the port 9080.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings-port
//     spec:
//       host: ratings.prod.svc.cluster.local
//       trafficPolicy: # Apply to all ports
//         portLevelSettings:
//         - port:
//             number: 80
//           loadBalancer:
//             simple: LEAST_CONN
//         - port:
//             number: 9080
//           loadBalancer:
//             simple: ROUND_ROBIN
//
type DestinationRule struct {
	// REQUIRED. The name of a service from the service registry. Service
	// names are looked up from the platform's service registry (e.g.,
	// Kubernetes services, Consul services, etc.) and from the hosts
	// declared by [ServiceEntries](#ServiceEntry). Rules defined for
	// services that do not exist in the service registry will be ignored.
	//
	// *Note for Kubernetes users*: When short names are used (e.g. "reviews"
	// instead of "reviews.default.svc.cluster.local"), Istio will interpret
	// the short name based on the namespace of the rule, not the service. A
	// rule in the "default" namespace containing a host "reviews will be
	// interpreted as "reviews.default.svc.cluster.local", irrespective of
	// the actual namespace associated with the reviews service. _To avoid
	// potential misconfigurations, it is recommended to always use fully
	// qualified domain names over short names._
	//
	// Note that the host field applies to both HTTP and TCP services.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Traffic policies to apply (load balancing policy, connection pool
	// sizes, outlier detection).
	TrafficPolicy *TrafficPolicy `protobuf:"bytes,2,opt,name=traffic_policy" json:"traffic_policy,omitempty"`
	// One or more named sets that represent individual versions of a
	// service. Traffic policies can be overridden at subset level.
	Subsets []*Subset `protobuf:"bytes,3,rep,name=subsets" json:"subsets,omitempty"`
}

func (m *DestinationRule) Reset()                    { *m = DestinationRule{} }
func (m *DestinationRule) String() string            { return proto.CompactTextString(m) }
func (*DestinationRule) ProtoMessage()               {}
func (*DestinationRule) Descriptor() ([]byte, []int) { return fileDescriptorDestinationRule, []int{0} }

func (m *DestinationRule) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DestinationRule) GetTrafficPolicy() *TrafficPolicy {
	if m != nil {
		return m.TrafficPolicy
	}
	return nil
}

func (m *DestinationRule) GetSubsets() []*Subset {
	if m != nil {
		return m.Subsets
	}
	return nil
}

// Traffic policies to apply for a specific destination, across all
// destination ports. See DestinationRule for examples.
type TrafficPolicy struct {
	// Settings controlling the load balancer algorithms.
	LoadBalancer *LoadBalancerSettings `protobuf:"bytes,1,opt,name=load_balancer" json:"load_balancer,omitempty"`
	// Settings controlling the volume of connections to an upstream service
	ConnectionPool *ConnectionPoolSettings `protobuf:"bytes,2,opt,name=connection_pool" json:"connection_pool,omitempty"`
	// Settings controlling eviction of unhealthy hosts from the load balancing pool
	OutlierDetection *OutlierDetection `protobuf:"bytes,3,opt,name=outlier_detection" json:"outlier_detection,omitempty"`
	// TLS related settings for connections to the upstream service.
	Tls *TLSSettings `protobuf:"bytes,4,opt,name=tls" json:"tls,omitempty"`
	// Traffic policies specific to individual ports. Note that port level
	// settings will override the destination-level settings. Traffic
	// settings specified at the destination-level will not be inherited when
	// overridden by port-level settings, i.e. default values will be applied
	// to fields omitted in port-level traffic policies.
	PortLevelSettings []*TrafficPolicy_PortTrafficPolicy `protobuf:"bytes,5,rep,name=port_level_settings" json:"port_level_settings,omitempty"`
}

func (m *TrafficPolicy) Reset()                    { *m = TrafficPolicy{} }
func (m *TrafficPolicy) String() string            { return proto.CompactTextString(m) }
func (*TrafficPolicy) ProtoMessage()               {}
func (*TrafficPolicy) Descriptor() ([]byte, []int) { return fileDescriptorDestinationRule, []int{1} }

func (m *TrafficPolicy) GetLoadBalancer() *LoadBalancerSettings {
	if m != nil {
		return m.LoadBalancer
	}
	return nil
}

func (m *TrafficPolicy) GetConnectionPool() *ConnectionPoolSettings {
	if m != nil {
		return m.ConnectionPool
	}
	return nil
}

func (m *TrafficPolicy) GetOutlierDetection() *OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *TrafficPolicy) GetTls() *TLSSettings {
	if m != nil {
		return m.Tls
	}
	return nil
}

func (m *TrafficPolicy) GetPortLevelSettings() []*TrafficPolicy_PortTrafficPolicy {
	if m != nil {
		return m.PortLevelSettings
	}
	return nil
}

// Traffic policies that apply to specific ports of the service
type TrafficPolicy_PortTrafficPolicy struct {
	// Specifies the port name or number of a port on the destination service
	// on which this policy is being applied.
	//
	// Names must comply with DNS label syntax (rfc1035) and therefore cannot
	// collide with numbers. If there are multiple ports on a service with
	// the same protocol the names should be of the form <protocol-name>-<DNS
	// label>.
	Port *PortSelector `protobuf:"bytes,1,opt,name=port" json:"port,omitempty"`
	// Settings controlling the load balancer algorithms.
	LoadBalancer *LoadBalancerSettings `protobuf:"bytes,2,opt,name=load_balancer" json:"load_balancer,omitempty"`
	// Settings controlling the volume of connections to an upstream service
	ConnectionPool *ConnectionPoolSettings `protobuf:"bytes,3,opt,name=connection_pool" json:"connection_pool,omitempty"`
	// Settings controlling eviction of unhealthy hosts from the load balancing pool
	OutlierDetection *OutlierDetection `protobuf:"bytes,4,opt,name=outlier_detection" json:"outlier_detection,omitempty"`
	// TLS related settings for connections to the upstream service.
	Tls *TLSSettings `protobuf:"bytes,5,opt,name=tls" json:"tls,omitempty"`
}

func (m *TrafficPolicy_PortTrafficPolicy) Reset()         { *m = TrafficPolicy_PortTrafficPolicy{} }
func (m *TrafficPolicy_PortTrafficPolicy) String() string { return proto.CompactTextString(m) }
func (*TrafficPolicy_PortTrafficPolicy) ProtoMessage()    {}
func (*TrafficPolicy_PortTrafficPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{1, 0}
}

func (m *TrafficPolicy_PortTrafficPolicy) GetPort() *PortSelector {
	if m != nil {
		return m.Port
	}
	return nil
}

func (m *TrafficPolicy_PortTrafficPolicy) GetLoadBalancer() *LoadBalancerSettings {
	if m != nil {
		return m.LoadBalancer
	}
	return nil
}

func (m *TrafficPolicy_PortTrafficPolicy) GetConnectionPool() *ConnectionPoolSettings {
	if m != nil {
		return m.ConnectionPool
	}
	return nil
}

func (m *TrafficPolicy_PortTrafficPolicy) GetOutlierDetection() *OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *TrafficPolicy_PortTrafficPolicy) GetTls() *TLSSettings {
	if m != nil {
		return m.Tls
	}
	return nil
}

// A subset of endpoints of a service. Subsets can be used for scenarios
// like A/B testing, or routing to a specific version of a service. Refer
// to [VirtualService](#VirtualService) documentation for examples of using
// subsets in these scenarios. In addition, traffic policies defined at the
// service-level can be overridden at a subset-level. The following rule
// uses a round robin load balancing policy for all traffic going to a
// subset named testversion that is composed of endpoints (e.g., pods) with
// labels (version:v3).
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       host: ratings.prod.svc.cluster.local
//       trafficPolicy:
//         loadBalancer:
//           simple: LEAST_CONN
//       subsets:
//       - name: testversion
//         labels:
//           version: v3
//         trafficPolicy:
//           loadBalancer:
//             simple: ROUND_ROBIN
//
// **Note:** Policies specified for subsets will not take effect until
// a route rule explicitly sends traffic to this subset.
type Subset struct {
	// REQUIRED. Name of the subset. The service name and the subset name can
	// be used for traffic splitting in a route rule.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// REQUIRED. Labels apply a filter over the endpoints of a service in the
	// service registry. See route rules for examples of usage.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Traffic policies that apply to this subset. Subsets inherit the
	// traffic policies specified at the DestinationRule level. Settings
	// specified at the subset level will override the corresponding settings
	// specified at the DestinationRule level.
	TrafficPolicy *TrafficPolicy `protobuf:"bytes,3,opt,name=traffic_policy" json:"traffic_policy,omitempty"`
}

func (m *Subset) Reset()                    { *m = Subset{} }
func (m *Subset) String() string            { return proto.CompactTextString(m) }
func (*Subset) ProtoMessage()               {}
func (*Subset) Descriptor() ([]byte, []int) { return fileDescriptorDestinationRule, []int{2} }

func (m *Subset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Subset) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Subset) GetTrafficPolicy() *TrafficPolicy {
	if m != nil {
		return m.TrafficPolicy
	}
	return nil
}

// Load balancing policies to apply for a specific destination. See Envoy's
// load balancing
// [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing.html)
// for more details.
//
// For example, the following rule uses a round robin load balancing policy
// for all traffic going to the ratings service.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       host: ratings.prod.svc.cluster.local
//       trafficPolicy:
//         loadBalancer:
//           simple: ROUND_ROBIN
//
// The following example uses the consistent hashing based load balancer
// for the same ratings service using the Cookie header as the hash key.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       host: ratings.prod.svc.cluster.local
//       trafficPolicy:
//         loadBalancer:
//           consistentHash:
//             http_header: Cookie
//
type LoadBalancerSettings struct {
	// Upstream load balancing policy.
	//
	// Types that are valid to be assigned to LbPolicy:
	//	*LoadBalancerSettings_Simple
	//	*LoadBalancerSettings_ConsistentHash
	LbPolicy isLoadBalancerSettings_LbPolicy `protobuf_oneof:"lb_policy"`
}

func (m *LoadBalancerSettings) Reset()         { *m = LoadBalancerSettings{} }
func (m *LoadBalancerSettings) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerSettings) ProtoMessage()    {}
func (*LoadBalancerSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{3}
}

type isLoadBalancerSettings_LbPolicy interface {
	isLoadBalancerSettings_LbPolicy()
}

type LoadBalancerSettings_Simple struct {
	Simple LoadBalancerSettings_SimpleLB `protobuf:"varint,1,opt,name=simple,proto3,enum=istio.LoadBalancerSettings_SimpleLB,oneof"`
}
type LoadBalancerSettings_ConsistentHash struct {
	ConsistentHash *LoadBalancerSettings_ConsistentHashLB `protobuf:"bytes,2,opt,name=consistent_hash,oneof"`
}

func (*LoadBalancerSettings_Simple) isLoadBalancerSettings_LbPolicy()         {}
func (*LoadBalancerSettings_ConsistentHash) isLoadBalancerSettings_LbPolicy() {}

func (m *LoadBalancerSettings) GetLbPolicy() isLoadBalancerSettings_LbPolicy {
	if m != nil {
		return m.LbPolicy
	}
	return nil
}

func (m *LoadBalancerSettings) GetSimple() LoadBalancerSettings_SimpleLB {
	if x, ok := m.GetLbPolicy().(*LoadBalancerSettings_Simple); ok {
		return x.Simple
	}
	return LoadBalancerSettings_ROUND_ROBIN
}

func (m *LoadBalancerSettings) GetConsistentHash() *LoadBalancerSettings_ConsistentHashLB {
	if x, ok := m.GetLbPolicy().(*LoadBalancerSettings_ConsistentHash); ok {
		return x.ConsistentHash
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LoadBalancerSettings) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _LoadBalancerSettings_OneofMarshaler, _LoadBalancerSettings_OneofUnmarshaler, _LoadBalancerSettings_OneofSizer, []interface{}{
		(*LoadBalancerSettings_Simple)(nil),
		(*LoadBalancerSettings_ConsistentHash)(nil),
	}
}

func _LoadBalancerSettings_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*LoadBalancerSettings)
	// lb_policy
	switch x := m.LbPolicy.(type) {
	case *LoadBalancerSettings_Simple:
		_ = b.EncodeVarint(1<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Simple))
	case *LoadBalancerSettings_ConsistentHash:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConsistentHash); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("LoadBalancerSettings.LbPolicy has unexpected type %T", x)
	}
	return nil
}

func _LoadBalancerSettings_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*LoadBalancerSettings)
	switch tag {
	case 1: // lb_policy.simple
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.LbPolicy = &LoadBalancerSettings_Simple{LoadBalancerSettings_SimpleLB(x)}
		return true, err
	case 2: // lb_policy.consistent_hash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoadBalancerSettings_ConsistentHashLB)
		err := b.DecodeMessage(msg)
		m.LbPolicy = &LoadBalancerSettings_ConsistentHash{msg}
		return true, err
	default:
		return false, nil
	}
}

func _LoadBalancerSettings_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*LoadBalancerSettings)
	// lb_policy
	switch x := m.LbPolicy.(type) {
	case *LoadBalancerSettings_Simple:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Simple))
	case *LoadBalancerSettings_ConsistentHash:
		s := proto.Size(x.ConsistentHash)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Consistent hashing (ketama hash) based load balancer for even load
// distribution/redistribution when the connection pool changes. This
// load balancing policy is applicable only for HTTP-based
// connections. A user specified HTTP header is used as the key with
// [xxHash](http://cyan4973.github.io/xxHash) hashing.
type LoadBalancerSettings_ConsistentHashLB struct {
	// REQUIRED. The name of the HTTP request header that will be used to
	// obtain the hash key. If the request header is not present, the load
	// balancer will use a random number as the hash, effectively making
	// the load balancing policy random.
	HttpHeader string `protobuf:"bytes,1,opt,name=http_header,proto3" json:"http_header,omitempty"`
	// The minimum number of virtual nodes to use for the hash
	// ring. Defaults to 1024. Larger ring sizes result in more granular
	// load distributions. If the number of hosts in the load balancing
	// pool is larger than the ring size, each host will be assigned a
	// single virtual node.
	MinimumRingSize uint32 `protobuf:"varint,2,opt,name=minimum_ring_size,proto3" json:"minimum_ring_size,omitempty"`
}

func (m *LoadBalancerSettings_ConsistentHashLB) Reset()         { *m = LoadBalancerSettings_ConsistentHashLB{} }
func (m *LoadBalancerSettings_ConsistentHashLB) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerSettings_ConsistentHashLB) ProtoMessage()    {}
func (*LoadBalancerSettings_ConsistentHashLB) Descriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{3, 0}
}

func (m *LoadBalancerSettings_ConsistentHashLB) GetHttpHeader() string {
	if m != nil {
		return m.HttpHeader
	}
	return ""
}

func (m *LoadBalancerSettings_ConsistentHashLB) GetMinimumRingSize() uint32 {
	if m != nil {
		return m.MinimumRingSize
	}
	return 0
}

// Connection pool settings for an upstream host. The settings apply to
// each individual host in the upstream service.  See Envoy's [circuit
// breaker](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/circuit_breaking)
// for more details. Connection pool settings can be applied at the TCP
// level as well as at HTTP level.
//
// For example, the following rule sets a limit of 100 connections to redis
// service called myredissrv with a connect timeout of 30ms
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-redis
//     spec:
//       host: myredissrv.prod.svc.cluster.local
//       trafficPolicy:
//         connectionPool:
//           tcp:
//             maxConnections: 100
//             connectTimeout: 30ms
//
type ConnectionPoolSettings struct {
	// Settings common to both HTTP and TCP upstream connections.
	Tcp *ConnectionPoolSettings_TCPSettings `protobuf:"bytes,1,opt,name=tcp" json:"tcp,omitempty"`
	// HTTP connection pool settings.
	Http *ConnectionPoolSettings_HTTPSettings `protobuf:"bytes,2,opt,name=http" json:"http,omitempty"`
}

func (m *ConnectionPoolSettings) Reset()         { *m = ConnectionPoolSettings{} }
func (m *ConnectionPoolSettings) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolSettings) ProtoMessage()    {}
func (*ConnectionPoolSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{4}
}

func (m *ConnectionPoolSettings) GetTcp() *ConnectionPoolSettings_TCPSettings {
	if m != nil {
		return m.Tcp
	}
	return nil
}

func (m *ConnectionPoolSettings) GetHttp() *ConnectionPoolSettings_HTTPSettings {
	if m != nil {
		return m.Http
	}
	return nil
}

// Settings common to both HTTP and TCP upstream connections.
type ConnectionPoolSettings_TCPSettings struct {
	// Maximum number of HTTP1 /TCP connections to a destination host.
	MaxConnections int32 `protobuf:"varint,1,opt,name=max_connections,proto3" json:"max_connections,omitempty"`
	// TCP connection timeout.
	ConnectTimeout *Duration `protobuf:"bytes,2,opt,name=connect_timeout" json:"connect_timeout,omitempty"`
}

func (m *ConnectionPoolSettings_TCPSettings) Reset()         { *m = ConnectionPoolSettings_TCPSettings{} }
func (m *ConnectionPoolSettings_TCPSettings) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolSettings_TCPSettings) ProtoMessage()    {}
func (*ConnectionPoolSettings_TCPSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{4, 0}
}

func (m *ConnectionPoolSettings_TCPSettings) GetMaxConnections() int32 {
	if m != nil {
		return m.MaxConnections
	}
	return 0
}

func (m *ConnectionPoolSettings_TCPSettings) GetConnectTimeout() *Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

// Settings applicable to HTTP1.1/HTTP2/GRPC connections.
type ConnectionPoolSettings_HTTPSettings struct {
	// Maximum number of pending HTTP requests to a destination. Default 1024.
	Http1MaxPendingRequests int32 `protobuf:"varint,1,opt,name=http1_max_pending_requests,proto3" json:"http1_max_pending_requests,omitempty"`
	// Maximum number of requests to a backend. Default 1024.
	Http2MaxRequests int32 `protobuf:"varint,2,opt,name=http2_max_requests,proto3" json:"http2_max_requests,omitempty"`
	// Maximum number of requests per connection to a backend. Setting this
	// parameter to 1 disables keep alive.
	MaxRequestsPerConnection int32 `protobuf:"varint,3,opt,name=max_requests_per_connection,proto3" json:"max_requests_per_connection,omitempty"`
	// Maximum number of retries that can be outstanding to all hosts in a
	// cluster at a given time. Defaults to 3.
	MaxRetries int32 `protobuf:"varint,4,opt,name=max_retries,proto3" json:"max_retries,omitempty"`
}

func (m *ConnectionPoolSettings_HTTPSettings) Reset()         { *m = ConnectionPoolSettings_HTTPSettings{} }
func (m *ConnectionPoolSettings_HTTPSettings) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolSettings_HTTPSettings) ProtoMessage()    {}
func (*ConnectionPoolSettings_HTTPSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{4, 1}
}

func (m *ConnectionPoolSettings_HTTPSettings) GetHttp1MaxPendingRequests() int32 {
	if m != nil {
		return m.Http1MaxPendingRequests
	}
	return 0
}

func (m *ConnectionPoolSettings_HTTPSettings) GetHttp2MaxRequests() int32 {
	if m != nil {
		return m.Http2MaxRequests
	}
	return 0
}

func (m *ConnectionPoolSettings_HTTPSettings) GetMaxRequestsPerConnection() int32 {
	if m != nil {
		return m.MaxRequestsPerConnection
	}
	return 0
}

func (m *ConnectionPoolSettings_HTTPSettings) GetMaxRetries() int32 {
	if m != nil {
		return m.MaxRetries
	}
	return 0
}

// A Circuit breaker implementation that tracks the status of each
// individual host in the upstream service.  While currently applicable to
// only HTTP services, future versions will support opaque TCP services as
// well. For HTTP services, hosts that continually return errors for API
// calls are ejected from the pool for a pre-defined period of time. See
// Envoy's [outlier
// detection](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/outlier)
// for more details.
//
// The following rule sets a connection pool size of 100 connections and
// 1000 concurrent HTTP2 requests, with no more than 10 req/connection to
// "reviews" service. In addition, it configures upstream hosts to be
// scanned every 5 mins, such that any host that fails 7 consecutive times
// with 5XX error code will be ejected for 15 minutes.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: reviews-cb-policy
//     spec:
//       host: reviews.prod.svc.cluster.local
//       trafficPolicy:
//         connectionPool:
//           tcp:
//             maxConnections: 100
//           http:
//             http2MaxRequests: 1000
//             maxRequestsPerConnection: 10
//         outlierDetection:
//           http:
//             consecutiveErrors: 7
//             interval: 5m
//             baseEjectionTime: 15m
//
type OutlierDetection struct {
	// Settings for HTTP1.1/HTTP2/GRPC connections.
	Http *OutlierDetection_HTTPSettings `protobuf:"bytes,1,opt,name=http" json:"http,omitempty"`
}

func (m *OutlierDetection) Reset()                    { *m = OutlierDetection{} }
func (m *OutlierDetection) String() string            { return proto.CompactTextString(m) }
func (*OutlierDetection) ProtoMessage()               {}
func (*OutlierDetection) Descriptor() ([]byte, []int) { return fileDescriptorDestinationRule, []int{5} }

func (m *OutlierDetection) GetHttp() *OutlierDetection_HTTPSettings {
	if m != nil {
		return m.Http
	}
	return nil
}

// Outlier detection settings for HTTP1.1/HTTP2/GRPC connections.
type OutlierDetection_HTTPSettings struct {
	// Number of 5XX errors before a host is ejected from the connection
	// pool. Defaults to 5.
	ConsecutiveErrors int32 `protobuf:"varint,1,opt,name=consecutive_errors,proto3" json:"consecutive_errors,omitempty"`
	// Time interval between ejection sweep analysis. format:
	// 1h/1m/1s/1ms. MUST BE >=1ms. Default is 10s.
	Interval *Duration `protobuf:"bytes,2,opt,name=interval" json:"interval,omitempty"`
	// Minimum ejection duration. A host will remain ejected for a period
	// equal to the product of minimum ejection duration and the number of
	// times the host has been ejected. This technique allows the system to
	// automatically increase the ejection period for unhealthy upstream
	// servers. format: 1h/1m/1s/1ms. MUST BE >=1ms. Default is 30s.
	BaseEjectionTime *Duration `protobuf:"bytes,3,opt,name=base_ejection_time" json:"base_ejection_time,omitempty"`
	// Maximum % of hosts in the load balancing pool for the upstream
	// service that can be ejected. Defaults to 10%.
	MaxEjectionPercent int32 `protobuf:"varint,4,opt,name=max_ejection_percent,proto3" json:"max_ejection_percent,omitempty"`
}

func (m *OutlierDetection_HTTPSettings) Reset()         { *m = OutlierDetection_HTTPSettings{} }
func (m *OutlierDetection_HTTPSettings) String() string { return proto.CompactTextString(m) }
func (*OutlierDetection_HTTPSettings) ProtoMessage()    {}
func (*OutlierDetection_HTTPSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDestinationRule, []int{5, 0}
}

func (m *OutlierDetection_HTTPSettings) GetConsecutiveErrors() int32 {
	if m != nil {
		return m.ConsecutiveErrors
	}
	return 0
}

func (m *OutlierDetection_HTTPSettings) GetInterval() *Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *OutlierDetection_HTTPSettings) GetBaseEjectionTime() *Duration {
	if m != nil {
		return m.BaseEjectionTime
	}
	return nil
}

func (m *OutlierDetection_HTTPSettings) GetMaxEjectionPercent() int32 {
	if m != nil {
		return m.MaxEjectionPercent
	}
	return 0
}

// SSL/TLS related settings for upstream connections. See Envoy's [TLS
// context](https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster_ssl.html#config-cluster-manager-cluster-ssl)
// for more details. These settings are common to both HTTP and TCP upstreams.
//
// For example, the following rule configures a client to use mutual TLS
// for connections to upstream database cluster.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: db-mtls
//     spec:
//       host: mydbserver.prod.svc.cluster.local
//       trafficPolicy:
//         tls:
//           mode: MUTUAL
//           clientCertificate: /etc/certs/myclientcert.pem
//           privateKey: /etc/certs/client_private_key.pem
//           caCertificates: /etc/certs/rootcacerts.pem
//
// The following rule configures a client to use TLS when talking to a
// foreign service whose domain matches *.foo.com.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: tls-foo
//     spec:
//       host: "*.foo.com"
//       trafficPolicy:
//         tls:
//           mode: SIMPLE
//
type TLSSettings struct {
	// REQUIRED: Indicates whether connections to this port should be secured
	// using TLS. The value of this field determines how TLS is enforced.
	Mode TLSSettings_TLSmode `protobuf:"varint,1,opt,name=mode,proto3,enum=istio.TLSSettings_TLSmode" json:"mode,omitempty"`
	// REQUIRED if mode is `MUTUAL`. The path to the file holding the
	// client-side TLS certificate to use.
	ClientCertificate string `protobuf:"bytes,2,opt,name=client_certificate,proto3" json:"client_certificate,omitempty"`
	// REQUIRED if mode is `MUTUAL`. The path to the file holding the
	// client's private key.
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,proto3" json:"private_key,omitempty"`
	// OPTIONAL: The path to the file containing certificate authority
	// certificates to use in verifying a presented server certificate. If
	// omitted, the proxy will not verify the server's certificate.
	CaCertificates string `protobuf:"bytes,4,opt,name=ca_certificates,proto3" json:"ca_certificates,omitempty"`
	// A list of alternate names to verify the subject identity in the
	// certificate. If specified, the proxy will verify that the server
	// certificate's subject alt name matches one of the specified values.
	SubjectAltNames []string `protobuf:"bytes,5,rep,name=subject_alt_names" json:"subject_alt_names,omitempty"`
	// SNI string to present to the server during TLS handshake.
	Sni string `protobuf:"bytes,6,opt,name=sni,proto3" json:"sni,omitempty"`
}

func (m *TLSSettings) Reset()                    { *m = TLSSettings{} }
func (m *TLSSettings) String() string            { return proto.CompactTextString(m) }
func (*TLSSettings) ProtoMessage()               {}
func (*TLSSettings) Descriptor() ([]byte, []int) { return fileDescriptorDestinationRule, []int{6} }

func (m *TLSSettings) GetMode() TLSSettings_TLSmode {
	if m != nil {
		return m.Mode
	}
	return TLSSettings_DISABLE
}

func (m *TLSSettings) GetClientCertificate() string {
	if m != nil {
		return m.ClientCertificate
	}
	return ""
}

func (m *TLSSettings) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *TLSSettings) GetCaCertificates() string {
	if m != nil {
		return m.CaCertificates
	}
	return ""
}

func (m *TLSSettings) GetSubjectAltNames() []string {
	if m != nil {
		return m.SubjectAltNames
	}
	return nil
}

func (m *TLSSettings) GetSni() string {
	if m != nil {
		return m.Sni
	}
	return ""
}

func init() {
	proto.RegisterType((*DestinationRule)(nil), "istio.DestinationRule")
	proto.RegisterType((*TrafficPolicy)(nil), "istio.TrafficPolicy")
	proto.RegisterType((*TrafficPolicy_PortTrafficPolicy)(nil), "istio.TrafficPolicy.PortTrafficPolicy")
	proto.RegisterType((*Subset)(nil), "istio.Subset")
	proto.RegisterType((*LoadBalancerSettings)(nil), "istio.LoadBalancerSettings")
	proto.RegisterType((*LoadBalancerSettings_ConsistentHashLB)(nil), "istio.LoadBalancerSettings.ConsistentHashLB")
	proto.RegisterType((*ConnectionPoolSettings)(nil), "istio.ConnectionPoolSettings")
	proto.RegisterType((*ConnectionPoolSettings_TCPSettings)(nil), "istio.ConnectionPoolSettings.TCPSettings")
	proto.RegisterType((*ConnectionPoolSettings_HTTPSettings)(nil), "istio.ConnectionPoolSettings.HTTPSettings")
	proto.RegisterType((*OutlierDetection)(nil), "istio.OutlierDetection")
	proto.RegisterType((*OutlierDetection_HTTPSettings)(nil), "istio.OutlierDetection.HTTPSettings")
	proto.RegisterType((*TLSSettings)(nil), "istio.TLSSettings")
	proto.RegisterEnum("istio.LoadBalancerSettings_SimpleLB", LoadBalancerSettings_SimpleLB_name, LoadBalancerSettings_SimpleLB_value)
	proto.RegisterEnum("istio.TLSSettings_TLSmode", TLSSettings_TLSmode_name, TLSSettings_TLSmode_value)
}

func init() {
	proto.RegisterFile("github.com/costinm/dmesh/dm/istio/destination_rule.proto", fileDescriptorDestinationRule)
}

var fileDescriptorDestinationRule = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0x22, 0x47,
	0x10, 0x36, 0x0c, 0xe0, 0x75, 0xcd, 0xda, 0xe0, 0xb6, 0x15, 0xb3, 0xb3, 0xf9, 0xf1, 0x92, 0x55,
	0xe4, 0x4d, 0x1c, 0xac, 0x10, 0x69, 0x63, 0xe5, 0x66, 0x8c, 0xb5, 0x58, 0xc2, 0x06, 0x79, 0xf0,
	0x25, 0x97, 0x56, 0x33, 0xb4, 0x4d, 0x27, 0x3d, 0xd3, 0x93, 0xee, 0x1e, 0x14, 0xe7, 0x09, 0x72,
	0xcb, 0x35, 0xa7, 0x3c, 0x44, 0xde, 0x26, 0xc7, 0x9c, 0xf2, 0x08, 0xb9, 0x46, 0xdd, 0xd3, 0xb0,
	0x78, 0x59, 0xbc, 0xab, 0xbd, 0xa1, 0xaa, 0xef, 0xab, 0xae, 0xfa, 0xa8, 0xaf, 0x06, 0x8e, 0x6f,
	0x99, 0x9e, 0x64, 0xa3, 0x66, 0x24, 0xe2, 0xa3, 0x48, 0x28, 0xcd, 0x92, 0xf8, 0x68, 0x1c, 0x53,
	0x35, 0x39, 0x1a, 0xc7, 0x47, 0x4c, 0x69, 0x26, 0x8e, 0xc6, 0xd4, 0x84, 0x89, 0x66, 0x22, 0xc1,
	0x32, 0xe3, 0xb4, 0x99, 0x4a, 0xa1, 0x05, 0x2a, 0xdb, 0x6c, 0x70, 0xf8, 0xee, 0x02, 0x23, 0xa2,
	0x1c, 0x29, 0xf8, 0xee, 0xdd, 0xe8, 0x29, 0x93, 0x3a, 0x23, 0x1c, 0x2b, 0x2a, 0xa7, 0x2c, 0x72,
	0xc4, 0x46, 0x0c, 0xd5, 0xce, 0xeb, 0x3e, 0xae, 0x32, 0x4e, 0xd1, 0x63, 0x28, 0x4d, 0x84, 0xd2,
	0xf5, 0xc2, 0x7e, 0xe1, 0x60, 0x03, 0x1d, 0xc2, 0x96, 0x96, 0xe4, 0xe6, 0x86, 0x45, 0x38, 0x15,
	0x9c, 0x45, 0x77, 0xf5, 0xe2, 0x7e, 0xe1, 0xc0, 0x6f, 0xed, 0x36, 0x6d, 0xd9, 0xe6, 0x30, 0x4f,
	0x0e, 0x6c, 0x0e, 0x7d, 0x0a, 0xeb, 0x2a, 0x1b, 0x29, 0xaa, 0x55, 0xdd, 0xdb, 0xf7, 0x0e, 0xfc,
	0xd6, 0xa6, 0x83, 0x85, 0x36, 0xda, 0xf8, 0xbd, 0x04, 0x9b, 0xf7, 0x19, 0x2d, 0xd8, 0xe4, 0x82,
	0x8c, 0xf1, 0x88, 0x70, 0x92, 0x44, 0x54, 0xda, 0x67, 0xfd, 0xd6, 0x53, 0xc7, 0xeb, 0x09, 0x32,
	0x6e, 0xbb, 0x54, 0x48, 0xb5, 0x66, 0xc9, 0xad, 0x42, 0x2f, 0xa1, 0x1a, 0x89, 0x24, 0xa1, 0x91,
	0xd5, 0x2e, 0x15, 0x82, 0xbb, 0xa6, 0x3e, 0x71, 0xac, 0xd3, 0x79, 0x76, 0x20, 0x04, 0x9f, 0xf3,
	0x5a, 0xb0, 0x2d, 0x32, 0xcd, 0x19, 0x95, 0x78, 0x4c, 0x75, 0x0e, 0xa8, 0x7b, 0x96, 0xb9, 0xe7,
	0x98, 0xfd, 0x3c, 0xdf, 0x99, 0xa5, 0xd1, 0x67, 0xe0, 0x69, 0xae, 0xea, 0x25, 0x8b, 0x42, 0xb3,
	0xa1, 0x7b, 0xe1, 0xbc, 0xe8, 0x29, 0xec, 0xa4, 0x42, 0x6a, 0xcc, 0xe9, 0x94, 0x1a, 0x75, 0xf3,
	0x70, 0xbd, 0x6c, 0xc7, 0xff, 0xe2, 0x6d, 0x2a, 0x35, 0x07, 0x42, 0xea, 0x7b, 0x91, 0xe0, 0xbf,
	0x02, 0x6c, 0x2f, 0x45, 0xd1, 0x33, 0x28, 0x99, 0xd2, 0x4e, 0x92, 0x1d, 0x57, 0xcb, 0xe0, 0x42,
	0xca, 0x69, 0xa4, 0x85, 0x5c, 0x96, 0xaf, 0xf8, 0x41, 0xf2, 0x79, 0x1f, 0x2c, 0x5f, 0xe9, 0xbd,
	0xe4, 0x2b, 0xaf, 0x92, 0xaf, 0xf1, 0x67, 0x01, 0x2a, 0xf9, 0x72, 0x98, 0xc5, 0x4b, 0x48, 0x4c,
	0xdd, 0xe2, 0xbd, 0x80, 0x0a, 0x27, 0x23, 0xca, 0x55, 0xbd, 0x68, 0xa5, 0x7c, 0x72, 0x6f, 0x93,
	0x9a, 0x3d, 0x9b, 0x3b, 0x4b, 0xb4, 0xbc, 0x7b, 0xcb, 0x8e, 0x7a, 0xab, 0x77, 0x34, 0xf8, 0x1a,
	0xfc, 0x45, 0xb2, 0x0f, 0xde, 0x4f, 0xf4, 0xce, 0x3d, 0xba, 0x09, 0xe5, 0x29, 0xe1, 0x19, 0xb5,
	0x32, 0x6e, 0x7c, 0x5f, 0x3c, 0x2e, 0x34, 0xfe, 0x2a, 0xc2, 0xee, 0x0a, 0x19, 0x2b, 0x8a, 0xc5,
	0x29, 0xcf, 0x1b, 0xde, 0x6a, 0x3d, 0x7f, 0x40, 0xf3, 0x66, 0x68, 0x91, 0xbd, 0x76, 0x77, 0x0d,
	0xbd, 0xb2, 0xf2, 0x2b, 0xa6, 0x34, 0x4d, 0x34, 0x9e, 0x10, 0x35, 0x71, 0x7f, 0xda, 0xe1, 0x43,
	0x05, 0x4e, 0xe7, 0x94, 0x2e, 0x51, 0x13, 0x53, 0x28, 0x68, 0x43, 0xed, 0xcd, 0x28, 0xda, 0x01,
	0x7f, 0xa2, 0x75, 0x8a, 0x27, 0x94, 0x8c, 0x9d, 0x99, 0x36, 0xd0, 0x13, 0xd8, 0x8e, 0x59, 0xc2,
	0xe2, 0x2c, 0xc6, 0x92, 0x25, 0xb7, 0x58, 0xb1, 0x5f, 0xf3, 0x09, 0x37, 0x1b, 0x5d, 0x78, 0x34,
	0x6b, 0x0d, 0x55, 0xc1, 0xbf, 0xea, 0x5f, 0x5f, 0x76, 0xf0, 0x55, 0xbf, 0x7d, 0x7e, 0x59, 0x5b,
	0x43, 0x5b, 0x00, 0xbd, 0xb3, 0x93, 0x70, 0x88, 0x4f, 0xfb, 0x97, 0x97, 0xb5, 0x02, 0x02, 0xa8,
	0x5c, 0x9d, 0x5c, 0x76, 0xfa, 0x17, 0xb5, 0xa2, 0x01, 0x0f, 0x4e, 0xc2, 0x70, 0xd8, 0xbd, 0xea,
	0x5f, 0xbf, 0xea, 0xd6, 0xbc, 0xb6, 0x0f, 0x1b, 0x7c, 0xe4, 0xf4, 0x6f, 0xfc, 0x5b, 0x84, 0x8f,
	0x56, 0x6c, 0xd1, 0x4b, 0xf0, 0x74, 0x94, 0xba, 0x9d, 0x7e, 0xf1, 0xe0, 0xc6, 0x35, 0x87, 0xa7,
	0x83, 0x39, 0xef, 0x18, 0x4a, 0x66, 0x32, 0xa7, 0xd5, 0x97, 0x0f, 0x13, 0xbb, 0xc3, 0xe1, 0x9c,
	0x19, 0x0c, 0xc0, 0x5f, 0x2c, 0xb4, 0x07, 0xd5, 0x98, 0xfc, 0x82, 0x5f, 0x5b, 0x40, 0xd9, 0x66,
	0xca, 0xe8, 0x60, 0xee, 0x0b, 0xac, 0x59, 0x4c, 0x45, 0xa6, 0xdd, 0x63, 0x55, 0xf7, 0x58, 0x27,
	0x93, 0xf6, 0x4c, 0x06, 0xbf, 0x15, 0xe0, 0xf1, 0xe2, 0x13, 0xa8, 0x01, 0x81, 0x69, 0xee, 0x1b,
	0x6c, 0x2a, 0xa7, 0x34, 0x19, 0x1b, 0x99, 0x25, 0xfd, 0x39, 0xa3, 0x4a, 0xcf, 0xca, 0x07, 0x80,
	0x0c, 0xa6, 0x65, 0x31, 0xf3, 0x5c, 0xd1, 0xe6, 0x3e, 0x87, 0xa7, 0x8b, 0x51, 0x9c, 0x52, 0xb9,
	0xd0, 0xa0, 0x5d, 0xe7, 0xb2, 0xf9, 0x6f, 0x73, 0x90, 0x96, 0x8c, 0xe6, 0x27, 0xa9, 0xdc, 0xf8,
	0xa7, 0x00, 0xb5, 0x25, 0xd7, 0xb5, 0x9c, 0x56, 0xb9, 0xc8, 0xcf, 0x57, 0x98, 0xf3, 0xbe, 0x4a,
	0x7f, 0xbc, 0x39, 0x53, 0x00, 0xc8, 0xec, 0x29, 0x8d, 0x32, 0xcd, 0xa6, 0x14, 0x53, 0x29, 0x85,
	0x9c, 0xcd, 0xf2, 0x0c, 0x1e, 0xb1, 0x44, 0x53, 0x39, 0x25, 0x7c, 0x85, 0x46, 0xe8, 0x2b, 0x40,
	0xe6, 0x03, 0x85, 0xe9, 0x8f, 0xee, 0xd0, 0x18, 0x4d, 0x9d, 0x31, 0x97, 0xc0, 0x1f, 0xc3, 0xae,
	0x19, 0x6d, 0x8e, 0x4d, 0xa9, 0x8c, 0x68, 0xa2, 0xdd, 0x8c, 0x7f, 0x17, 0xc0, 0x5f, 0x3c, 0xb9,
	0x07, 0x50, 0x8a, 0xc5, 0x78, 0xe6, 0xbb, 0x60, 0xf9, 0xaa, 0x98, 0xdf, 0x06, 0x61, 0x67, 0xe0,
	0xcc, 0xf8, 0x2c, 0xa2, 0x52, 0xb3, 0x1b, 0x16, 0x11, 0xed, 0xcc, 0x6d, 0xe4, 0x4c, 0x25, 0x9b,
	0x12, 0x4d, 0xb1, 0x39, 0x00, 0x9e, 0x0d, 0xee, 0x41, 0x35, 0x22, 0x8b, 0xe0, 0x5c, 0x67, 0xeb,
	0x21, 0x95, 0x8d, 0x4c, 0x7f, 0x98, 0x70, 0x8d, 0xcd, 0xa1, 0xca, 0x8f, 0xfc, 0x86, 0xb9, 0x20,
	0x2a, 0x61, 0xf5, 0x8a, 0xc1, 0x35, 0x9a, 0xb0, 0x3e, 0x7b, 0xdc, 0x87, 0xf5, 0xce, 0x79, 0x78,
	0xd2, 0xee, 0x9d, 0xd5, 0xd6, 0x8c, 0x77, 0xc2, 0xf3, 0x8b, 0x41, 0xef, 0x2c, 0xf7, 0xd1, 0xc5,
	0xf5, 0xf0, 0xfa, 0xa4, 0x57, 0x2b, 0xb6, 0xd7, 0x7f, 0xc8, 0x3f, 0xf8, 0xa3, 0x8a, 0xfd, 0x20,
	0x7f, 0xfb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0x96, 0x12, 0xe0, 0x3a, 0x08, 0x00, 0x00,
}
