// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/costinm/dmesh/dm/istio/service_entry.proto

package istio

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Location specifies whether the service is part of Istio mesh or
// outside the mesh.  Location determines the behavior of several
// features, such as service-to-service mTLS authentication, policy
// enforcement, etc. When communicating with services outside the mesh,
// Istio's mTLS authentication is disabled, and policy enforcement is
// performed on the client-side as opposed to server-side.
type ServiceEntry_Location int32

const (
	// Signifies that the service is external to the mesh. Typically used
	// to indicate external services consumed through APIs.
	ServiceEntry_MESH_EXTERNAL ServiceEntry_Location = 0
	// Signifies that the service is part of the mesh. Typically used to
	// indicate services added explicitly as part of expanding the service
	// mesh to include unmanaged infrastructure (e.g., VMs added to a
	// Kubernetes based service mesh).
	ServiceEntry_MESH_INTERNAL ServiceEntry_Location = 1
)

var ServiceEntry_Location_name = map[int32]string{
	0: "MESH_EXTERNAL",
	1: "MESH_INTERNAL",
}
var ServiceEntry_Location_value = map[string]int32{
	"MESH_EXTERNAL": 0,
	"MESH_INTERNAL": 1,
}

func (x ServiceEntry_Location) String() string {
	return proto.EnumName(ServiceEntry_Location_name, int32(x))
}
func (ServiceEntry_Location) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorServiceEntry, []int{0, 0}
}

// Resolution determines how the proxy will resolve the IP addresses of
// the network endpoints associated with the service, so that it can
// route to one of them. The resolution mode specified here has no impact
// on how the application resolves the IP address associated with the
// service. The application may still have to use DNS to resolve the
// service to an IP so that the outbound traffic can be captured by the
// Proxy. Alternatively, for HTTP services, the application could
// directly communicate with the proxy (e.g., by setting HTTP_PROXY) to
// talk to these services.
type ServiceEntry_Resolution int32

const (
	// Assume that incoming connections have already been resolved (to a
	// specific destination IP address). Such connections are typically
	// routed via the proxy using mechanisms such as IP table REDIRECT/
	// eBPF. After performing any routing related transformations, the
	// proxy will forward the connection to the IP address to which the
	// connection was bound.
	ServiceEntry_NONE ServiceEntry_Resolution = 0
	// Use the static IP addresses specified in endpoints (see below) as the
	// backing instances associated with the service.
	ServiceEntry_STATIC ServiceEntry_Resolution = 1
	// Attempt to resolve the IP address by querying the ambient DNS,
	// during request processing. If no endpoints are specified, the proxy
	// will resolve the DNS address specified in the hosts field, if
	// wildcards are not used. If endpoints are specified, the DNS
	// addresses specified in the endpoints will be resolved to determine
	// the destination IP address.
	ServiceEntry_DNS ServiceEntry_Resolution = 2
)

var ServiceEntry_Resolution_name = map[int32]string{
	0: "NONE",
	1: "STATIC",
	2: "DNS",
}
var ServiceEntry_Resolution_value = map[string]int32{
	"NONE":   0,
	"STATIC": 1,
	"DNS":    2,
}

func (x ServiceEntry_Resolution) String() string {
	return proto.EnumName(ServiceEntry_Resolution_name, int32(x))
}
func (ServiceEntry_Resolution) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorServiceEntry, []int{0, 1}
}

// `ServiceEntry` enables adding additional entries into Istio's internal
// service registry, so that auto-discovered services in the mesh can
// access/route to these manually specified services. A service entry
// describes the properties of a service (DNS name, VIPs ,ports, protocols,
// endpoints). These services could be external to the mesh (e.g., web
// APIs) or mesh-internal services that are not part of the platform's
// service registry (e.g., a set of VMs talking to services in Kubernetes).
//
// The following configuration adds a set of MongoDB instances running on
// unmanaged VMs to Istio's registry, so that these services can be treated
// as any other service in the mesh. The associated DestinationRule is used
// to initiate mTLS connections to the database instances.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: ServiceEntry
//     metadata:
//       name: external-svc-mongocluster
//     spec:
//       hosts:
//       - mymongodb.somedomain # not used
//       addresses:
//       - 192.192.192.192/24 # VIPs
//       ports:
//       - number: 27018
//         name: mongodb
//         protocol: MONGO
//       location: MESH_INTERNAL
//       resolution: STATIC
//       endpoints:
//       - address: 2.2.2.2
//       - address: 3.3.3.3
//
// and the associated DestinationRule
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: mtls-mongocluster
//     spec:
//       host: mymongodb.somedomain
//       trafficPolicy:
//         tls:
//           mode: MUTUAL
//           clientCertificate: /etc/certs/myclientcert.pem
//           privateKey: /etc/certs/client_private_key.pem
//           caCertificates: /etc/certs/rootcacerts.pem
//
// The following example demonstrates the use of wildcards in the hosts for
// external services. If the connection has to be routed to the IP address
// requested by the application (i.e. application resolves DNS and attempts
// to connect to a specific IP), the discovery mode must be set to `NONE`.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: ServiceEntry
//     metadata:
//       name: external-svc-wildcard-example
//     spec:
//       hosts:
//       - "*.bar.com"
//       location: MESH_EXTERNAL
//       ports:
//       - number: 80
//         name: http
//         protocol: HTTP
//       resolution: NONE
//
// For HTTP based services, it is possible to create a VirtualService
// backed by multiple DNS addressable endpoints. In such a scenario, the
// application can use the HTTP_PROXY environment variable to transparently
// reroute API calls for the VirtualService to a chosen backend. For
// example, the following configuration creates a non-existent external
// service called foo.bar.com backed by three domains: us.foo.bar.com:8443,
// uk.foo.bar.com:9443, and in.foo.bar.com:7443
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: ServiceEntry
//     metadata:
//       name: external-svc-dns
//     spec:
//       hosts:
//       - foo.bar.com
//       location: MESH_EXTERNAL
//       ports:
//       - number: 443
//         name: https
//         protocol: HTTP
//       resolution: DNS
//       endpoints:
//       - address: us.foo.bar.com
//         ports:
//           https: 8443
//       - address: uk.foo.bar.com
//         ports:
//           https: 9443
//       - address: in.foo.bar.com
//         ports:
//           https: 7443
//
// and a DestinationRule to initiate TLS connections to the ServiceEntry.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: tls-foobar
//     spec:
//       host: foo.bar.com
//       trafficPolicy:
//         tls:
//           mode: SIMPLE # initiates HTTPS
//
// With HTTP_PROXY=http://localhost:443, calls from the application to
// http://foo.bar.com will be upgraded to HTTPS and load balanced across
// the three domains specified above. In other words, a call to
// http://foo.bar.com/baz would be translated to
// https://uk.foo.bar.com/baz.
type ServiceEntry struct {
	// REQUIRED. The hosts associated with the ServiceEntry. Could be a DNS
	// name with wildcard prefix (external services only). DNS names in hosts
	// will be ignored if the application accesses the service over non-HTTP
	// protocols such as mongo/opaque TCP/even HTTPS. In such scenarios, the
	// IP addresses specified in the Addresses field or the port will be used
	// to uniquely identify the destination.
	Hosts []string `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	// The virtual IP addresses associated with the service. Could be CIDR
	// prefix.  For HTTP services, the addresses field will be ignored and
	// the destination will be identified based on the HTTP Host/Authority
	// header. For non-HTTP protocols such as mongo/opaque TCP/even HTTPS,
	// the hosts will be ignored. If one or more IP addresses are specified,
	// the incoming traffic will be idenfified as belonging to this service
	// if the destination IP matches the IP/CIDRs specified in the addresses
	// field. If the Addresses field is empty, traffic will be identified
	// solely based on the destination port. In such scenarios, the port on
	// which the service is being accessed must not be shared by any other
	// service in the mesh. In other words, the sidecar will behave as a
	// simple TCP proxy, forwarding incoming traffic on a specified port to
	// the specified destination endpoint IP/host.
	Addresses []string `protobuf:"bytes,2,rep,name=addresses" json:"addresses,omitempty"`
	// REQUIRED. The ports associated with the external service.
	Ports []*Port `protobuf:"bytes,3,rep,name=ports" json:"ports,omitempty"`
	// Specify whether the service should be considered external to the mesh
	// or part of the mesh.
	Location ServiceEntry_Location `protobuf:"varint,4,opt,name=location,proto3,enum=istio.ServiceEntry_Location" json:"location,omitempty"`
	// Service discovery mode for the hosts. If not set, Istio will attempt
	// to infer the discovery mode based on the value of hosts and endpoints.
	Resolution ServiceEntry_Resolution `protobuf:"varint,5,opt,name=resolution,proto3,enum=istio.ServiceEntry_Resolution" json:"resolution,omitempty"`
	// One or more endpoints associated with the service.
	Endpoints []*ServiceEntry_Endpoint `protobuf:"bytes,6,rep,name=endpoints" json:"endpoints,omitempty"`
}

func (m *ServiceEntry) Reset()                    { *m = ServiceEntry{} }
func (m *ServiceEntry) String() string            { return proto.CompactTextString(m) }
func (*ServiceEntry) ProtoMessage()               {}
func (*ServiceEntry) Descriptor() ([]byte, []int) { return fileDescriptorServiceEntry, []int{0} }

func (m *ServiceEntry) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *ServiceEntry) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *ServiceEntry) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ServiceEntry) GetLocation() ServiceEntry_Location {
	if m != nil {
		return m.Location
	}
	return ServiceEntry_MESH_EXTERNAL
}

func (m *ServiceEntry) GetResolution() ServiceEntry_Resolution {
	if m != nil {
		return m.Resolution
	}
	return ServiceEntry_NONE
}

func (m *ServiceEntry) GetEndpoints() []*ServiceEntry_Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// Endpoint defines a network address (IP or hostname) associated with
// the mesh service.
type ServiceEntry_Endpoint struct {
	// REQUIRED: Address associated with the network endpoint without the
	// port ( IP or fully qualified domain name without wildcards). Domain
	// names can be used if and only if the resolution is set to DNS.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Set of ports associated with the endpoint. The ports must be
	// associated with a port name that was declared as part of the
	// service.
	Ports map[string]uint32 `protobuf:"bytes,2,rep,name=ports" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// One or more labels associated with the endpoint.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ServiceEntry_Endpoint) Reset()         { *m = ServiceEntry_Endpoint{} }
func (m *ServiceEntry_Endpoint) String() string { return proto.CompactTextString(m) }
func (*ServiceEntry_Endpoint) ProtoMessage()    {}
func (*ServiceEntry_Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptorServiceEntry, []int{0, 0}
}

func (m *ServiceEntry_Endpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceEntry_Endpoint) GetPorts() map[string]uint32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ServiceEntry_Endpoint) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceEntry)(nil), "istio.ServiceEntry")
	proto.RegisterType((*ServiceEntry_Endpoint)(nil), "istio.ServiceEntry.Endpoint")
	proto.RegisterEnum("istio.ServiceEntry_Location", ServiceEntry_Location_name, ServiceEntry_Location_value)
	proto.RegisterEnum("istio.ServiceEntry_Resolution", ServiceEntry_Resolution_name, ServiceEntry_Resolution_value)
}

func init() {
	proto.RegisterFile("github.com/costinm/dmesh/dm/istio/service_entry.proto", fileDescriptorServiceEntry)
}

var fileDescriptorServiceEntry = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x8f, 0x9a, 0x40,
	0x1c, 0xc5, 0x1d, 0x10, 0x84, 0x3f, 0xa5, 0xc5, 0x39, 0x11, 0xd2, 0x34, 0xc4, 0x4b, 0x49, 0xda,
	0x42, 0x63, 0xd3, 0xc6, 0xf4, 0x66, 0x5b, 0x92, 0x9a, 0xb8, 0xec, 0x46, 0x3c, 0x6c, 0xf6, 0x62,
	0x10, 0x26, 0x4a, 0x16, 0x18, 0xc3, 0x8c, 0x6e, 0xfc, 0x50, 0xfb, 0xc5, 0xf6, 0x53, 0x6c, 0x1c,
	0xd1, 0x70, 0x30, 0xee, 0x71, 0xde, 0xbc, 0xdf, 0x9b, 0xf9, 0xbf, 0xfc, 0xe1, 0xe7, 0x2a, 0xe7,
	0xeb, 0xed, 0xd2, 0x4f, 0x69, 0x19, 0xa4, 0x94, 0xf1, 0xbc, 0x2a, 0x83, 0xac, 0x24, 0x6c, 0x1d,
	0x64, 0x65, 0x90, 0x33, 0x9e, 0xd3, 0x80, 0x91, 0x7a, 0x97, 0xa7, 0x64, 0x41, 0x2a, 0x5e, 0xef,
	0xfd, 0x4d, 0x4d, 0x39, 0xc5, 0x8a, 0xb8, 0x72, 0x82, 0xb7, 0xe9, 0x55, 0xc2, 0xc9, 0x53, 0xd2,
	0x70, 0x83, 0xe7, 0x2e, 0xbc, 0x8b, 0x8f, 0x79, 0xe1, 0x21, 0x0e, 0x9b, 0xa0, 0xac, 0x29, 0xe3,
	0xcc, 0x46, 0xae, 0xec, 0xe9, 0xb8, 0x0f, 0x7a, 0x92, 0x65, 0x35, 0x61, 0x8c, 0x30, 0x5b, 0x12,
	0x92, 0x03, 0xca, 0x86, 0xd6, 0x9c, 0xd9, 0xb2, 0x2b, 0x7b, 0xc6, 0xd0, 0xf0, 0x45, 0xae, 0x7f,
	0x47, 0x6b, 0x8e, 0x7d, 0xd0, 0x0a, 0x9a, 0x26, 0x3c, 0xa7, 0x95, 0xdd, 0x75, 0x91, 0xf7, 0x7e,
	0xf8, 0xb1, 0xb9, 0x6e, 0x3f, 0xe2, 0x4f, 0x1b, 0x0f, 0x1e, 0x02, 0xd4, 0x84, 0xd1, 0x62, 0x2b,
	0x08, 0x45, 0x10, 0x9f, 0x2e, 0x11, 0xb3, 0xb3, 0x0b, 0x07, 0xa0, 0x93, 0x2a, 0xdb, 0xd0, 0xbc,
	0xe2, 0xcc, 0x56, 0xc5, 0x1f, 0x2e, 0x3e, 0x12, 0x36, 0x26, 0xe7, 0x05, 0x81, 0x76, 0x3a, 0xe0,
	0x0f, 0xd0, 0x6b, 0x06, 0xb2, 0x91, 0x8b, 0x3c, 0x1d, 0xff, 0x3a, 0x8d, 0x23, 0x89, 0xa8, 0xcf,
	0xd7, 0xa2, 0xc4, 0x90, 0xec, 0x58, 0xd4, 0x08, 0xd4, 0x22, 0x59, 0x92, 0xe2, 0xd4, 0x83, 0x77,
	0x15, 0x9c, 0x0a, 0xab, 0x10, 0x9d, 0xaf, 0x00, 0xad, 0x1c, 0x03, 0xe4, 0x47, 0xb2, 0x6f, 0x3e,
	0x63, 0x82, 0xb2, 0x4b, 0x8a, 0x2d, 0xb1, 0x25, 0x17, 0x79, 0xe6, 0x6f, 0x69, 0x84, 0x9c, 0x6f,
	0x60, 0xb4, 0xe0, 0x2b, 0x76, 0xfd, 0x60, 0x1f, 0x7c, 0x07, 0xed, 0xdc, 0x6e, 0x1f, 0xcc, 0x9b,
	0x30, 0xfe, 0xbf, 0x08, 0xef, 0xe7, 0xe1, 0x2c, 0x1a, 0x4f, 0xad, 0xce, 0x59, 0x9a, 0x44, 0x8d,
	0x84, 0x06, 0x5f, 0x00, 0x5a, 0xed, 0x6a, 0xd0, 0x8d, 0x6e, 0xa3, 0xd0, 0xea, 0x60, 0x00, 0x35,
	0x9e, 0x8f, 0xe7, 0x93, 0xbf, 0x16, 0xc2, 0x3d, 0x90, 0xff, 0x45, 0xb1, 0x25, 0xfd, 0xe9, 0x3d,
	0x1c, 0x37, 0x6d, 0xa9, 0x8a, 0xfd, 0xf9, 0xf1, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xc9, 0x9c,
	0xb7, 0xb0, 0x02, 0x00, 0x00,
}
