apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: dev
#build:
#  artifacts:
#  - image: gcr.io/dmeshgate/sshc
#    context: ..
#    custom:
#      buildCommand: make build gcp/push
#      dependencies:
#        paths:
#        - sshc/**
#        - manifests/sshd/**
deploy:
  helm:
    releases:
    - name: dev
      chartPath: dev
      #artifactOverrides:
      #  image: gcr.io/dmeshgate/sshc:latest

      namespace: dev
      createNamespace: true
#portForward:
#- resourceType: deployment
#  resourceName: ssh-ca
#  namespace: ssh-ca
#  port: 8080
#  localPort: 14021
#- resourceType: deployment
#  resourceName: ssh-ca
#  namespace: ssh-ca
#  port: 8081
#  localPort: 14020
#- resourceType: deployment
#  resourceName: sshd
#  namespace: sshd
#  port: 15022
#  localPort: 14022
